#!/usr/bin/env python3
"""Adversarial System Null Ladder for the frozen CEOS v0.1 specifications."""
from __future__ import annotations
import copy,hashlib,json
from pathlib import Path
import yaml
from jsonschema import Draft202012Validator
ROOT=Path(__file__).resolve().parents[1];SCHEMA=ROOT/'schemas/cross_mapping_passport.schema.json';EXAMPLE=ROOT/'config/cross_mapping_passport.example.json';TYPECFG=ROOT/'config/claim_type_system_v0.1.yaml';DOCCFG=ROOT/'config/document_contract_v0.1.yaml';OUT=ROOT/'derived/system_null_ladder_v0.1.json';MD=ROOT/'reports/system_null_ladder_v0.1.md'
def digest(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def passport_accepts(x,validator):
 errors=list(validator.iter_errors(x));checks=[]
 if not errors:
  s=x['mapping_stability'];m=s['maturity'];o=s['observed_across'];e=x['epistemic_effect']
  checks=[m!='NOT_TESTED' or not any(o.values()),m not in {'SINGLE_WORLD','MULTI_WORLD','INDEPENDENTLY_REPLICATED'} or o['one_world'],m not in {'MULTI_WORLD','INDEPENDLY_REPLICATED'} or o['multiple_worlds'],m!='INDEPENDENTLY_REPLICATED' or (o['independent_datasets'] and o['independent_observers']),m!='FAILED',x['cross_mapping_asymmetry_acknowledged'] is True,e['mapping_is_descriptive'] and not e['upgrades_source_ontology'] and not e['upgrades_target_ontology'] and e['independent_admitted_evidence_required_for_upgrade'],'prediction of untested properties' in x['interpretation_boundary']['does_not_support']]
 return not errors and all(checks),[e.message for e in errors],checks
def main():
 schema=json.loads(SCHEMA.read_text());base=json.loads(EXAMPLE.read_text());validator=Draft202012Validator(schema);results=[]
 def add(i,cls,severity,invalid_accepted,detail):results.append({'id':i,'class':cls,'severity':severity,'outcome':'BREACH' if invalid_accepted else 'SURVIVED','detail':detail})
 # Controls.
 ok,err,_=passport_accepts(copy.deepcopy(base),validator);results.append({'id':'CONTROL_VALID_PASSPORT','class':'control','severity':'CONTROL','outcome':'SURVIVED' if ok else 'CONTROL_FAILED','detail':f'valid accepted={ok}; errors={err}'})
 x=copy.deepcopy(base);x['cross_mapping_asymmetry_acknowledged']=False;ok,err,_=passport_accepts(x,validator);results.append({'id':'CONTROL_REMOVE_ASYMMETRY','class':'control','severity':'CONTROL','outcome':'SURVIVED' if not ok else 'CONTROL_FAILED','detail':f'invalid accepted={ok}; errors={err}'})
 # Status escalation with no mapping support.
 x=copy.deepcopy(base);x['status']='ADMITTED';ok,err,_=passport_accepts(x,validator);add('ADMITTED_WITHOUT_QUALIFICATION','status','CRITICAL',ok,f'accepted={ok}; maturity={x["mapping_stability"]["maturity"]}; targets empty')
 x=copy.deepcopy(base);x['evidence_strength']['level']='INDEPENDENTLY_REPLICATED';ok,_,_=passport_accepts(x,validator);add('GHOST_EVIDENCE','evidence','CRITICAL',ok,f'accepted={ok}; evidence artifact IDs={x["evidence_strength"]["independent_evidence_artifact_ids"]}')
 x=copy.deepcopy(base);x['mapping_provenance']['constructed_from']['relation_pattern']=True;ok,_,_=passport_accepts(x,validator);add('GHOST_PROVENANCE','provenance','HIGH',ok,f'accepted={ok}; source artifact IDs={x["mapping_provenance"]["source_artifact_ids"]}')
 a=copy.deepcopy(base);b=copy.deepcopy(base);b['direction']='CLASSICAL_TO_CEOS';oka,_,_=passport_accepts(a,validator);okb,_,_=passport_accepts(b,validator);same_endpoints=a['source']==b['source'] and a['target']==b['target'];add('DIRECTION_SEMANTIC_NOOP','direction','HIGH',oka and okb and same_endpoints,f'both accepted={oka and okb}; endpoints unchanged={same_endpoints}')
 x=copy.deepcopy(base);x['mapping_stability']['qualification_outcome']='PASS';ok,_,_=passport_accepts(x,validator);add('NOT_TESTED_PLUS_PASS','maturity','HIGH',ok,f'accepted={ok}; maturity NOT_TESTED + outcome PASS')
 x=copy.deepcopy(base);x['status']='ADMITTED';x['mapping_stability']['maturity']='SINGLE_WORLD';x['mapping_stability']['qualification_outcome']='FAILED';x['mapping_stability']['observed_across']['one_world']=True;ok,_,_=passport_accepts(x,validator);add('ADMITTED_PLUS_FAILED','status','CRITICAL',ok,f'accepted={ok}; ADMITTED + latest FAILED')
 x=copy.deepcopy(base);x['interpretation_boundary']['supports'].append('physical mechanism');ok,_,_=passport_accepts(x,validator);add('CONTRADICTORY_INTERPRETATION_BOUNDARY','semantics','CRITICAL',ok,f'accepted={ok}; physical mechanism in Supports and Does-not-support')
 x=copy.deepcopy(base);x['interpretation_boundary']['supports'].append('evidence inheritance through vocabulary mapping');ok,_,_=passport_accepts(x,validator);add('EVIDENCE_INHERITANCE_SMUGGLING','semantics','CRITICAL',ok,f'accepted={ok}; asymmetry boolean true while Supports imports evidence')
 x=copy.deepcopy(base);x['status']='ADMITTED';x['mapping_stability']['maturity']='SINGLE_WORLD';x['mapping_stability']['qualification_outcome']='PASS';x['mapping_stability']['observed_across']['one_world']=True;ok,_,_=passport_accepts(x,validator);add('UNSEARCHED_COUNTEREXAMPLES','qualification','HIGH',ok and not any(x['mapping_stability']['counterexample_search'].values()),f'accepted={ok}; searches={x["mapping_stability"]["counterexample_search"]}')
 x=copy.deepcopy(base);x['mapping_stability']['maturity']='INDEPENDENTLY_REPLICATED';x['mapping_stability']['qualification_outcome']='PASS';x['mapping_stability']['observed_across']={k:True for k in x['mapping_stability']['observed_across']};ok,_,_=passport_accepts(x,validator);add('HISTORYLESS_INDEPENDENT_REPLICATION','lifecycle','CRITICAL',ok,f'accepted={ok}; schema has no qualification history')
 add('INDEPENDENCE_WITHOUT_IDENTITIES','independence','CRITICAL',ok,f'accepted={ok}; no WORLD/dataset/Observer identity fields exist')
 # Document scope and semantic lint attacks.
 doccfg=yaml.safe_load(DOCCFG.read_text())['ceos_document_contract'];includes=doccfg['scope']['include'];json_covered=any('json' in p.lower() for p in includes);add('NON_MARKDOWN_CLAIM_ESCAPE','artifact_scope','CRITICAL',not json_covered,f'claim-bearing JSON covered={json_covered}; include={includes}')
 mark='<!-- CEOS-INTERPRETATION-BOUNDARY v0.1 -->';synthetic=f'''# Adversarial\n\n{mark}\n## Interpretation Boundary — Document Scope\n### Supports\n- physical mechanism.\n### Does not support\n- physical mechanism;\n- prediction of untested properties.\n### Cross Mapping Asymmetry\nVocabulary correspondence ≠ evidence inheritance.\n''';tail=synthetic.split(mark,1)[1];lint_pass=('### Supports' in tail and '### Does not support' in tail and 'prediction of untested properties' in tail and 'Vocabulary correspondence ≠ evidence inheritance.' in tail);add('SEMANTIC_MARKDOWN_CONTRADICTION','document_semantics','CRITICAL',lint_pass,f'current structural linter accepts contradictory Supports/Does-not-support={lint_pass}')
 # Claim graph and typing attacks.
 typecfg=yaml.safe_load(TYPECFG.read_text())['claim_type_system'];graph={'A':['B'],'B':['A']};has_graph_rule=any('acyclic' in str(v).lower() for v in typecfg.values());add('CYCLIC_CLAIM_GRAPH','claim_graph','CRITICAL',not has_graph_rule,f'cycle A↔B; acyclicity rule present={has_graph_rule}')
 req=typecfg['transitions']['OrganizationalObject_to_FrozenFamily']['requires'];self_asserted={r:True for r in req};transition_accepts=all(self_asserted.values());add('SELF_ASSERTED_TRANSITION_EVIDENCE','typing','CRITICAL',transition_accepts,f'boolean-only evidence accepted={transition_accepts}; no artifact verification')
 has_pin=any(any(q in str(v).lower() for q in ['content hash','content_hash','digest']) for v in typecfg.values());add('UNPINNED_ANTECEDENT','versioning','HIGH',not has_pin,f'content/version pin rule present={has_pin}')
 breaches=[r for r in results if r['outcome']=='BREACH'];survived=[r for r in results if r['outcome']=='SURVIVED'];report={'protocol':'system_null_ladder_v0.1','target_hashes':{str(p.relative_to(ROOT)):digest(p) for p in [SCHEMA,TYPECFG,DOCCFG]},'attacks_total':len(results)-2,'breaches':len(breaches),'survived_invalid_attacks':sum(r['outcome']=='SURVIVED' and r['class']!='control' for r in results),'controls_passed':sum(r['outcome']=='SURVIVED' and r['class']=='control' for r in results),'results':results,'interpretation_boundary':{'supports':['identification of logical and validation gaps in frozen CEOS specifications'],'does_not_support':['proof that CEOS is universally unsound','physical mechanism','thermodynamic phase','microscopic Hamiltonian','prediction of untested properties'],'scope':'adversarial tests registered in system_null_ladder_v0.1'}}
 OUT.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
 lines=['# CEOS System Null Ladder v0.1 — Red-Team Report','','The target specifications were frozen before attack execution. `BREACH` means a logically invalid claim was accepted or escaped registered validation.','',f"- Invalid attacks: **{report['attacks_total']}**",f"- Breaches: **{report['breaches']}**",f"- Invalid attacks survived: **{report['survived_invalid_attacks']}**",f"- Controls passed: **{report['controls_passed']}/2**",'', '| Attack | Class | Severity | Outcome |','|---|---|---|---|']+[f"| `{r['id']}` | {r['class']} | {r['severity']} | **{r['outcome']}** |" for r in results]+['','## Breach details','']
 for r in breaches:lines += [f"### {r['id']}",'',r['detail'],'']
 lines += ['## Interpretation Boundary','','### Supports','','- identification of concrete logical gaps in the frozen v0.1 specification.','','### Does not support','','- a claim that every CEOS result is invalid;','- a physical mechanism or material interpretation;','- completeness of the adversarial attack set;','- prediction of untested properties.','','### Cross Mapping Asymmetry','','> **Vocabulary correspondence ≠ evidence inheritance.**']
 MD.write_text('\n'.join(lines)+'\n')
 print(json.dumps({'invalid_attacks':report['attacks_total'],'breaches':report['breaches'],'controls_passed':report['controls_passed'],'breach_ids':[r['id'] for r in breaches]},indent=2))
if __name__=='__main__':main()
